### PR TITLE
Update swagger-core

### LINKED ISSUE #206: Update swagger-core
This is tricky to do as the swagger json has changed format. Before the path `/api-docs` gave a list of paths to get the swagger json. For example `/api-docs/serviceA`.
In the new swagger json format, the whole json is at `/swagger.json`.

It means that the the `/dynamic` service generator needs to be totally refactored to enrigh the `swagger.json`.

The official dropwizard swagger integration can be found here:
https://github.com/swagger-api/swagger-samples/tree/master/java/java-dropwizard

### PR DESCRIPTION
**Pull request by benwbooth**
This pull request updates SciGraph's swagger implementation to use the new 2.0 spec. Backward compatibility is maintained in the cypherResources section of the custom yaml configuration. The code first attempts to parse the cypherResources as swagger 2.0. If that fails, it falls back to 1.2. So any existing yaml configuration should continue to work.

I also upgraded swagger-ui to be the newest version. I've tested viewing the swagger docs and as far as I can tell everything looks good.

This pull request fixes #206.

### CODE REVIEW

**Comment by cmungall** [comment]
@kshefchek I suggest we run some tests locally and deploy to dev. I believe that ci.monarchinitiative.org will auto-deploy to dev once we merge into master?

**Comment by kshefchek** [comment]
Sure, I'm not sure we trigger builds when master is updated: http://ci.monarchinitiative.org/view/dev/job/load-scigraph-data-on-dev/ but we are building the whole stack weekly, so as long as I can get the solr load to finish in a timely fashion.

**Comment by jnguyenx** [comment]
It does not built automatically from master, sometimes changes will require a graph reload. So it's a manual trigger to keep things in sync.

**Comment by kshefchek** [comment]
I booted this up locally and am having some html/css issues.  For example, when opening the graph -> neighbors service I do not see an input box for ID:

scigraph-swagger

Is this possibly a mvn build/dependency version issue?  I pulled from this branch and built scigraph via 'mvn package'

**Comment by benwbooth** [comment]
@kshefchek If you click the "Try it out" button, then all the input boxes appear. I think this is a different behavior than the old swagger-ui interface.

**Comment by kshefchek** [comment]
Got it working now, thanks!  Right now the services are in alphabetical order, is there a way to have them show up in the order they are in the configuration?  

All seems to be working as expected.

**Comment by benwbooth** [comment]
@kshefcheck:

> Got it working now, thanks! Right now the services are in alphabetical order, is there a way to have them show up in the order they are in the configuration?

Not yet, as far as I can tell:

https://github.com/swagger-api/swagger-ui/issues/2657
https://github.com/swagger-api/swagger-ui/issues/2990

I checked the latest source code for swagger-ui. It looks like it's grouping the operations using an unordered map, then iterates over the map which produces an alphabetical sorting. There is an `apisSorter` option but it doesn't look like it's implemented yet.

**Comment by benwbooth** [comment]
I tried to paste the swagger.json into the SmartAPI editor at http://smart-api.info/editor to fix #204 and https://github.com/biolink/biolink-api/issues/22 , but I'm seeing multiple incompatibilities between the swagger 2.0 spec and the schema SmartAPI expects:

- info / contacts:
swagger 2.0 allows for `name`, `url`, and `email` fields, but SmartAPI requires `responsibleDeveloper`, `responsibleOrganization`, `url`, and `email` fields.
- swagger 2.0 adds `body` parameters for each of the injected classes passed in to the constructor. SmartAPI complains that the `body` parameters have the same name. I *could* filter these out...

These changes would make our `swagger.json` incompatible with the swagger 2.0 spec. I'm not sure if the schema at https://github.com/WebsmartAPI/swagger-editor/blob/master/node_modules_changes/schema.json is an old version of the swagger 2.0 spec. Should we ask them to update their spec? Or should we generate a `/swagger.smartapi.json` with the required modifications, but keep `/swagger.json` for swagger docs?

Here is the swagger 2.0 schema and spec:
http://swagger.io/v2/schema.json
https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/2.0.md

and here is the smartAPI schema:
https://github.com/WebsmartAPI/swagger-editor/blob/master/node_modules_changes/schema.json

**Comment by TomConlin** [comment]
With a hackathon coming May 9,10,11 which is expecting to use the smart api  would it be better to stay the course till after?

**Comment by cmungall** [comment]
It's better to be conformant to the swagger 2.0 spec.

We can have a script (ugly) that produces a smartAPI conformant json from ours, but this seems awkward. I'll contact the smartAPI developers

**Comment by TomConlin** [comment]
+1

**Comment by kshefchek** [comment]
Looks like there are some small conflicts with your PR and https://github.com/SciGraph/SciGraph/pull/223, could you resolve these and update your PR?

**Comment by benwbooth** [comment]
I fixed the merge conflicts. Let me know if there's anything else I should do.

**Comment by cmungall** [comment]
@kshefchek can we deploy on dev? https://scigraph-ontology-dev.monarchinitiative.org/scigraph/docs/ still says to upgrade.

Then we can try swagger-codegen, Peter wants java client for annotator

**Comment by kshefchek** [comment]
Looks like I can't simply restart the service.  I'm reloading both data and ontology graphs now.

**Comment by kshefchek** [comment]
We're getting an error when restarting the scigraph service: http://ci.monarchinitiative.org/view/dev/job/start-scigraph-data-service-dev/69/ looking into it now.

**Comment by benwbooth** [comment]
There were some changes to the way SciGraph parses and stores swagger yaml metadata. It now uses the data modes defined by [SwaggerParser](https://github.com/swagger-api/swagger-parser) instead of custom beans. So that CypherResources test in monarch-cypher-queries will need to be updated.

**Comment by kshefchek** [comment]
Interesting, didn't realize we had tests here - https://github.com/monarch-initiative/monarch-cypher-queries/tree/master/src/test/java/org/monarchinitiative

I've added a ticket in that repo - https://github.com/monarch-initiative/monarch-cypher-queries/issues/12

**Comment by kshefchek** [comment]
@cmungall https://scigraph-ontology-dev.monarchinitiative.org/scigraph/docs/ is back up with the latest swagger.

**Pull request merged**
